{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "8.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.0.1.aar",
          "url": "databinding-adapters-8.0.1.aar",
          "size": 70378,
          "sha512": "18e9dccc1b55a22279579ef3f4d465c8c2a57f0be54f0003d35ab815b97ee9d5ab3afb62ade8c0be8ca9abdf73ca55cb6da16c86b197bdd37f255cc1a7476390",
          "sha256": "8efbc002dd64ce1c59b8deb66d1df5a89d9a3dc3ed116989194a09a47eeb3537",
          "sha1": "249803adfeabdfb0661a69e5945a6b947ba3b868",
          "md5": "88ddba5b63a2caaf2c3b3decdf5702f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.0.1.aar",
          "url": "databinding-adapters-8.0.1.aar",
          "size": 70378,
          "sha512": "18e9dccc1b55a22279579ef3f4d465c8c2a57f0be54f0003d35ab815b97ee9d5ab3afb62ade8c0be8ca9abdf73ca55cb6da16c86b197bdd37f255cc1a7476390",
          "sha256": "8efbc002dd64ce1c59b8deb66d1df5a89d9a3dc3ed116989194a09a47eeb3537",
          "sha1": "249803adfeabdfb0661a69e5945a6b947ba3b868",
          "md5": "88ddba5b63a2caaf2c3b3decdf5702f2"
        }
      ]
    }
  ]
}
