{
  "formatVersion": "1.1",
  "component": {
    "group": "com.firebaseui",
    "module": "firebase-ui-firestore",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-firestore"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-firestore-8.0.2.aar",
          "url": "firebase-ui-firestore-8.0.2.aar",
          "size": 26943,
          "sha512": "5a777b0b69d88319481ec014738576f9ddf589d311e477ec3a3643101ff9b2dc62b70ade86564dfbb8d3bd00ff3191762c188c9ddd0c5174d969e87e7c452446",
          "sha256": "cf61b5a24fda798420097e75c43e96e0f813b56bf508e8191a877c00b9d73bc7",
          "sha1": "55dc5bf77fff88ee84dcb537fc6be645c83721db",
          "md5": "2963b79f62a8bf690a12b78b76718607"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "28.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-firestore"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-firestore-8.0.2.aar",
          "url": "firebase-ui-firestore-8.0.2.aar",
          "size": 26943,
          "sha512": "5a777b0b69d88319481ec014738576f9ddf589d311e477ec3a3643101ff9b2dc62b70ade86564dfbb8d3bd00ff3191762c188c9ddd0c5174d969e87e7c452446",
          "sha256": "cf61b5a24fda798420097e75c43e96e0f813b56bf508e8191a877c00b9d73bc7",
          "sha1": "55dc5bf77fff88ee84dcb537fc6be645c83721db",
          "md5": "2963b79f62a8bf690a12b78b76718607"
        }
      ]
    }
  ]
}
